description: FMoW experiments for FedDrift, parameter settings

target:
  service: sing
  # run "amlt target list sing" to list the names of available AMLK8s targets
  name: msroctovc

# image must contain mpi and proper toolkit
# the following image runs the example pytorch_mnist
environment:
  image: amlt-sing/pytorch
  setup:
  - pip install wilds
  - pip install wandb
  - pip install mpi4py
  - pip install paho-mqtt
  - wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
  - mkdir -p ./data/fmow/data/
  - ./azcopy cp '$FMOW_TAR_PATH' ./data/fmow/data/
  - cd ./data/fmow/data/; tar xf fmow_v1.1.tar; cd ../../../

data:
    local_dir: ./data/fmow/data
    remote_dir: projects/cont_fedml/data

# storage:
#   output:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/t-chenningli

# TODO: rsimpai storage.  Requires a different task name
# storage:
#   models:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/models

#   data:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/data


code:
  # download the code for the example first:
  # python ./src/download_horovod_examples.py --example pytorch_mnist
  # remember to update the code using PT_OUTPUT_DIR to retrieve results using "pt results"
  # upload the code
  local_dir: .

jobs:
- name: feddrift-eager2
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_02 1 0 D

- name: feddrift2
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_02_0 1 0 D
  
- name: dsurf2
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 02 1 0 D

- name: feddrift-eager4
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_04 1 0 D

- name: feddrift4
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_04_0 1 0 D
  
- name: feddrift-eager6-larger-cap
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 12 0 0 softcluster mmacc_06 1 0 D

- name: feddrift6-larger-cap
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 12 0 0 softcluster H_A_F_1_06_0 1 0 D

- name: dsurf6
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 06 1 0 D

- name: feddrift-eager8
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_08 1 0 D

- name: feddrift8
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_08_0 1 0 D
  
- name: dsurf8
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 08 1 0 D

- name: feddrift-eager10
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_10 1 0 D

- name: feddrift10
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_10_0 1 0 D
  
- name: dsurf10
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 10 1 0 D
  
- name: feddrift-eager12
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_12 1 0 D

- name: feddrift12
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_12_0 1 0 D

- name: dsurf12
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 12 1 0 D
    
- name: feddrift-eager14
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_14 1 0 D

- name: feddrift14
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_14_0 1 0 D

- name: dsurf14
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 14 1 0 D
    
- name: feddrift-eager16
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_16 1 0 D

- name: feddrift16
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_16_0 1 0 D

- name: dsurf16
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 16 1 0 D
    
- name: feddrift-eager18
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_18 1 0 D

- name: feddrift18
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_18_0 1 0 D

- name: dsurf18
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 18 1 0 D
    
- name: feddrift-eager20
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softcluster mmacc_20 1 0 D

- name: feddrift20
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_F_1_20_0 1 0 D

- name: dsurf20
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 driftsurf 20 1 0 D
