description: FMoW experiments for FedDrift with more baselines, Trial 2

target:
  service: sing
  # run "amlt target list sing" to list the names of available AMLK8s targets
  name: msroctovc

# image must contain mpi and proper toolkit
# the following image runs the example pytorch_mnist
environment:
  image: amlt-sing/pytorch
  setup:
  - pip install wilds
  - pip install wandb
  - pip install mpi4py
  - pip install paho-mqtt
  - wget -O azcopy_v10.tar.gz https://aka.ms/downloadazcopy-v10-linux && tar -xf azcopy_v10.tar.gz --strip-components=1
  - mkdir -p ./data/fmow/data/
  - ./azcopy cp '$FMOW_TAR_PATH' ./data/fmow/data/
  - cd ./data/fmow/data/; tar xf fmow_v1.1.tar; cd ../../../

data:
    local_dir: ./data/fmow/data
    remote_dir: projects/cont_fedml/data

# storage:
#   output:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/t-chenningli

# TODO: rsimpai storage.  Requires a different task name
# storage:
#   models:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/models

#   data:
#     storage_account_name: mnrmlsys
#     container_name: amulet
#     mount_dir: /mnt/data


code:
  # download the code for the example first:
  # python ./src/download_horovod_examples.py --example pytorch_mnist
  # remember to update the code using PT_OUTPUT_DIR to retrieve results using "pt results"
  # upload the code
  local_dir: .

jobs:  
- name: win2
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_one
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 0 0 win-2 1 12 D
  
- name: weight-lin
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 1 0 0 lin dummy 1 12 D

- name: weight-exp
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 1 0 0 exp dummy 1 12 D
  
- name: aue-pc
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 auepc dummy 1 12 D
  
- name: cfl
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 5 0 0 softcluster cfl_0.1_all 1 12 D
  
- name: ifca
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 5 0 0 softcluster hard-r 1 12 D
  
- name: ifca-t
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 5 0 0 softcluster hard 1 12 D

- name: feddrift-eager-win
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 6 0 0 softclusterwin-1 mmacc_06 1 12 D

- name: feddrift-win
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softclusterwin-1 H_A_F_1_06_0 1 12 D
  
- name: feddrift-c
  sku: G4-V100
  command:
  - cd fedml_experiments/distributed/fedavg_cont_ens
  - ~/.local/bin/wandb login 215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee
  - export WANDB_API_KEY="215d78ccc4bfa4a30fcb4bc08ba10884e6e42fee"
  - ~/.local/bin/wandb online
  - bash run_fedavg_distributed_pytorch.sh 5 5 1 4 resnet homo 10 50 32 0.0001 fmow ../../../data/fmow/data/ 100 0 0 9 8 0 0 softcluster H_A_E_1_06_0 1 12 D
